#define IDC_MYICON                      2
#define IDD_CHIPSCHALLENGE_DIALOG       102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define MELINDA_MSG                     104
#define IDM_EXIT                        105
#define IDC_CHIPSCHALLENGE              109
#define IDR_MAINFRAME                   128
#define IDI_CHIPSCHALLENGE              130
#define IDB_BACKGROUND                  131
#define IDB_NUMBERS                     134
#define IDB_SCORE_BACKGROUND            135
#define IDB_SPRITES                     136
#define IDB_SPRITES_BLACKWHITE          138
#define IDB_TROPHY                      139
#define IDB_VICTORY                     140
#define IDD_BESTTIMES                   141
#define IDB_GAME_AREA_BACKGROUND        144
#define IDD_PASSENTRY                   145
#define IDD_GOTO                        146
#define IDB_LEVEL_TITLE_LEFT            147
#define IDB_LEVEL_TITLE_RIGHT           148
#define IDB_HINT_BACKGROUND             149
#define IDD_VICTORY                     150
#define ID_ABOUTTEXT_CONTAINER          1000
#define IDGOTO                          1001
#define IDC_LIST1                       1002
#define ID_SCORES_LIST                  1002
#define IDC_SCORES_LIST                 1002
#define TXT_LEVELS_COMPLETE             1003
#define TXT_TOTAL_SCORE                 1004
#define IDC_MAIN_BG                     1005
#define IDC_EDIT1                       1006
#define ID_PE_TEXT_ENTER                1006
#define TXT_GOTO_LEVEL                  1006
#define TXT_PASS_ENTRY                  1007
#define TXT_GOTO_PASS                   1007
#define IDC_MSG                         1007
#define IDC_TIMEBONUS                   1008
#define IDC_LVLBONUS                    1009
#define IDC_LVLSCORE                    1010
#define IDC_TOTALSCORE                  1011
#define IDC_MSG2                        1012
#define ID_GAME_PAUSE                   32771
#define ID_GAME_BESTTIMES               32772
#define ID_GAME_EXIT                    32773
#define ID_OPTIONS_BACKGROUNDMUSIC      32774
#define ID_OPTIONS_SOUNDEFFECTS         32775
#define ID_OPTIONS_COLOR                32776
#define ID_LEVEL_RESTART                32777
#define ID_LEVEL_NEXT                   32778
#define ID_LEVEL_PREVIOUS               32779
#define ID_LEVEL_GOTO                   32780
#define ID_HELP_HOWTOPLAY               32781
#define ID_HELP_COMMANDS                32782
#define ID_HELP_HOWTOUSEHELP            32783
#define ID_HELP_ABOUTCHIPSCHALLENGE     32784
#define IDM_GAME_NEWGAME                32785
#define ID_GAME_NEWGAME                 32789
#define ID_HELP_CONTENTS                32790
#define ID_ADD_IGNORE                   32794
#define ID_GAME_IGNOREPASSWORDS         32795
#define ID_GAME_ODDEVEN_LABEL           32798
#define ID_ADD_ODDEVEN_CONTROL          32799
#define IDC_STATIC                      -1

// Default values for new objects
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
